[package]
name = "kerberus-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
serde = { version = "1.0.159", features = ["derive"]}
serde_json = "1.0.95"
ureq = "2.6.2"
