# Generated by Django 4.1.7 on 2023-04-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dependency",
            fields=[
                ("package_name", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("version", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("name", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("dependencies", models.ManyToManyField(related_name="projects", to="core.dependency")),
            ],
        ),
        migrations.CreateModel(
            name="Ingest",
            fields=[
                ("hash_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("dependencies", models.ManyToManyField(related_name="ingests", to="core.dependency")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.project")),
            ],
        ),
        migrations.AddField(
            model_name="dependency",
            name="ingest",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.ingest"),
        ),
    ]
