# Generated by Django 4.1.7 on 2023-04-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dependency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=20)),
                ("ecosystem", models.CharField(choices=[("maven", "maven"), ("npm", "npm")], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("dependencies", models.ManyToManyField(related_name="projects", to="core.dependency")),
            ],
        ),
        migrations.CreateModel(
            name="Ingest",
            fields=[
                ("hash_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("ecosystem", models.CharField(choices=[("maven", "maven"), ("npm", "npm")], max_length=10)),
                ("dependencies", models.ManyToManyField(related_name="ingests", to="core.dependency")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.project")),
            ],
        ),
        migrations.AddField(
            model_name="dependency",
            name="ingest",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.ingest"),
        ),
    ]
