# Generated by Django 4.1.7 on 2023-05-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dependency",
            name="total_vulnerabilities",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dependency",
            name="total_vulnerabilities_critical",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dependency",
            name="total_vulnerabilities_high",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dependency",
            name="total_vulnerabilities_low",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dependency",
            name="total_vulnerabilities_medium",
            field=models.IntegerField(default=0),
        ),
    ]
